name: Deploy CloverOS with netinstall

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dark-mode index, manifest, and netinstall.lua
        run: |
          # --- Dark-mode index ---
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Index of CloverOS</title><style>
          body { background:#0d1117; color:#c9d1d9; font-family: monospace; padding:20px; }
          a { color:#58a6ff; text-decoration:none; }
          a:hover { text-decoration:underline; }
          h1 { color:#58a6ff; }
          hr { border:0; border-top:1px solid #30363d; }
          pre { line-height:1.6; }
          </style></head><body><h1>Index of CloverOS</h1><hr><pre>" > index.html

          # --- Initialize manifest ---
          > files.manifest

          # Find all files except .git, .github, index.html, workflow files
          find . -type f ! -path "./.git/*" ! -path "./.github/*" ! -name "index.html" ! -name "*.yml" | sort | while read -r file; do
              path=$(echo "$file" | sed 's|^\./||')
              name=$(basename "$path")
              base="${name%.*}"

              # Handle files without extension
              [ "$base" = "$name" ] && base="$name"

              # Skip empty paths
              [ -z "$base" ] && continue

              # Add file to index
              echo "<a href=\"$path\">$path</a>" >> index.html

              # Add to manifest
              echo "$path" >> files.manifest

              # Only create redirect folder if safe (no file/folder exists)
              if [ ! -e "$base" ] && [ ! -f "$base" ]; then
                  mkdir -p "$base"
                  echo "<!DOCTYPE html><html><head><meta http-equiv='refresh' content='0; url=../$path'></head><body></body></html>" > "$base/index.html"
              fi
          done

          echo "</pre><hr><footer>Generated automatically for CloverOS — Dark Mode Enabled</footer></body></html>" >> index.html

          # --- Generate netinstall.lua ---
          cat > netinstall.lua <<'EOF'
-- Netinstall for CloverOS
local http = require("http")
local fs = require("fs")

local baseURL = "https://palordersoftworksofficial.github.io/CloverOS/"
local manifestURL = baseURL .. "files.manifest"

local response = http.get(manifestURL)
if not response then
    print("Failed to fetch files manifest")
    return
end

local files = {}
for line in response.readAll():gmatch("[^\r\n]+") do
    table.insert(files, line)
end
response.close()

for _, file in ipairs(files) do
    local fileURL = baseURL .. file
    print("Downloading " .. file)
    local fResponse = http.get(fileURL)
    if fResponse then
        local content = fResponse.readAll()
        fResponse.close()
        local dir = file:match("(.*/)")
        if dir then fs.makeDir(dir) end
        local f = fs.open(file, "w")
        f.write(content)
        f.close()
    else
        print("Failed to download " .. file)
    end
end

print("All files downloaded successfully!")
EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
