name: Deploy full static file index to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dark-mode index and universal extensionless redirects
        run: |
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Index of CloverOS</title><style>
          body { background:#0d1117; color:#c9d1d9; font-family: monospace; padding:20px; }
          a { color:#58a6ff; text-decoration:none; }
          a:hover { text-decoration:underline; }
          h1 { color:#58a6ff; }
          hr { border:0; border-top:1px solid #30363d; }
          pre { line-height:1.6; }
          </style></head><body><h1>Index of CloverOS</h1><hr><pre>" > index.html

          # Find all files except .git, .github, and workflow files
          find . -type f ! -path "./.git/*" ! -path "./.github/*" ! -name "index.html" ! -name "*.yml" | sort | while read -r file; do
              path=$(echo "$file" | sed 's|^\./||')
              name=$(basename "$path")
              base="${name%.*}"

              # Handle files without extension
              if [ "$base" = "$name" ]; then
                  base="$name"
              fi

              # Skip empty paths
              [ -z "$base" ] && continue

              # Add file to main index
              echo "<a href=\"$path\">$path</a>" >> index.html

              # Only create redirect folder if safe (no file or folder exists)
              if [ ! -e "$base" ] && [ ! -f "$base" ]; then
                  mkdir -p "$base"
                  echo "<!DOCTYPE html><html><head><meta http-equiv='refresh' content='0; url=../$path'></head><body></body></html>" > "$base/index.html"
              fi
          done

          echo "</pre><hr><footer>Generated automatically for CloverOS — Dark Mode Enabled</footer></body></html>" >> index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
